FROM node:alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY ./node_modules ./
#COPY --chown=node:node ./package.json ./
#RUN npm install
#COPY --chown=node:node ./ ./

#COPY ./ ./

CMD ["npm", "start"]